#+STARTUP: overview
#+STARTUP: hidestars

* Tasks
** DONE Test org-mode install
   CLOSED: [2017-01-04 Wed 15:33]
** TODO How to org-mode
  More about [[http://doc.norang.ca/org-mode.html][here]]
*** Key combinations:
  Shift+Alt+Enter = creates a ** line
  * create headings and subheadings
  Ctrl+c Ctrl+t tags a TODO as DONE and adds a time stamp
  "[[link][description]" creates a link with the text given in "description" visible
  Shift+TAB opens or closes all sections
  Ctrl+c Ctrl+c to add TAGS
  Ctrl+c Ctrl+x Ctrl+i Clock-IN
  Ctrl+c Ctrl+x Ctrl+o Clock OUT

** TODO Finish Habil report!
** TODO Edit and Resubmit Polar Biology Manuscript
*** Description
    MS on the phylogeny of /Rossella/ was sent to Polar Biology and is currently accepted with changes. These changes have to be done and the MS needs to be resubmitted.
    
*** Changes to be done by section:
**** When you submit the revised manuscript, please also provide a detailed RESPONSE.
      1. As a general rule, your response should be as comprehensive as necessary and as succinct and lucid as possible.
      2. Please draft it in such a way that it is as easy as possible for reviewers and/or editor to evaluate how and where you incorporated a comment in your revised ms or why you did not adopt it.
      3. Please address EACH of the reviewers' remarks or suggestions step-by-step, by either incorporating it in your revision or, in case you disagree with it, concisely explaining your reasons in a rebuttal.
      4. Please do also respond explicitly to the format issues that I ask you to pay special attention to (see below).
      5. MOST IMPORTANTLY, please pay PARTICULAR attention to any general and severe criticisms that call for either profound revisions (more thorough than just fixing typos, modifying formats and/or improving style) or particularly well-founded rebuttals.
      6. Your response should comprise a COMPLETE POINT-BY-POINT LIST briefly describing how each comment or suggestion was addressed. Each list item should comprise
         - verbatim quote the referee's/editor's ENTIRE COMMENT (including, if applicable, the page and line numbers in your original ms, which it refers to),
         - followed by your response, starting with the word "REPLY", in which you briefly describe the action taken to address the comment by changing the ms in response to the suggestion (if applicable, including a verbatim quote of the modified text, preceded by page and line numbers in the revised ms)
	 - or why you disagree with the comment and, hence, did not change your ms.
      7. Do NOT respond with very general statements, such as "Almost all suggestions have been considered" or "The text has been changed", and ultra-short point-by-point replies like "OK" or "DONE". They are not helpful, since they will make the evaluation of your revision more difficult and time-consuming than necessary and thus inevitably lead to a delay in the final decision of your submission.
    - [ ] In addition to a revised 'clean' ms ("Revised Manuscript"), please also submit an ANNOTATED VERSION of the ms ("Marked Manuscript"), in which the changes you made are clearly indicated (e.g., by using Word's track changes or otherwise highlighting modified text passages) so that it is easy to check where and how you accepted the reviewer's/editor's suggestions and changed the text accordingly and where you did not. When you submit your revision, follow the order "Response", "Marked Manuscript" and "Revised Manuscript" (comprising text, tables and figures in separate files).
    - [ ] In general, I'd sincerely recommend to thoroughly and carefully PROOF-READ your ENTIRE ms (main text, reference list, table and figure legends, tables, figures) prior to final resubmission to rectify as many minor formal flaws as possible. When revising your ms, please strictly follow ALL FORMAT REQUIREMENTS of Polar Biology, as described in the detailed Instructions for Authors that you can find at our website (URL: http://www.springer.com/300).
    - [ ] According to our experience, the creation of a complete and formally correct REFERENCE LIST is a cumbersome task. Therefore, please check meticulously whether EACH citation is included in the literature list (and vice versa). You may also consider making use of the 'AUTOMATIC REFERENCE CHECKING', a module of the Editorial Manager that is provided to assist you in examining the validity of all the journal references in your literature list. Its results can be obtained by clicking the corresponding link in your Main Menu in the Editorial Manager, as well as in the fdf file containing your manuscript including text, tables and figures). This service should help you to identify incorrect list entries. If "not validated" is displayed for a the reference, it should be checked carefully and corrected where appropriate, as in most cases, typos, wrong journals, issues or pages precluded its validation.

    - [ ] In the revision of the ms, please pay special attention to the following issues (which you should refer to explicitly in your reply, explaining briefly how you addressed them in your revision):
      1. You have submitted your ms for publication as a Short Note. Please note that its length is currently not appropriate for this type of paper, which should not exceed 6 printed pages, including tables and illustrations [Note: one printed page corresponds to approx. 850 words text, or 3 illustrations with their legends, or 55 references; see http://www.springer.com/300/, link 'Instructions for Authors > Types of papers' for more detailed information]. Therefore, I recommend resubmitting the revised version as an Original Paper. Otherwise, you have to abridge the overall length of the ms considerably to comply with the length limitation of Short Notes. You may achieve this by shortening the text and/or reducing the number of references and/or attaching selected tables or figures, which provide useful but not indispensable information for the readers, as Electronic Supplementary Material (ESM) to your paper and refer to them in the running text as "Online Resource 1", "Online Resource 2", etc. (see Polar Biology's website at http://www.springer.com/300/, link 'Instructions for Authors > Electronic Supplementary Material', for more details on this matter).
      2. Do not number the headings of sections and sub-sections.
      3. A random non-exhaustive check of the literature list suggests that reference entries do NOT always exactly comply with the format requirements of Polar Biology. I'd like to ask you to comprehensively and meticulously check the entire literature list and rectify all non-compliant entries, paying CAREFUL ATTENTION to EVERY minuscule detail (e.g., always use correct journal abbreviations, heed punctuation rules (i.e., check absence and presence of dots, commas and blanks), do not give journal issue numbers, etc.). For more information on format requirements see www.springer.com/300, link 'Instruction of Authors > References'.
      4. Please check the proper use of scientific species names throughout the entire ms (title, headings, text, legends, tables, figures, reference list). Make sure the species and genus names are always italicized in print. Moreover, verify that they are written out as full names (e.g., Homo sapiens) in the Title, the first time they are used in the Abstract, and the first time they are used in the body of the paper, as well as in each table legend or each figure caption. Thereafter, in the body the names should be abbreviated as the first letter of the genus name (capitalized) and the complete specific epithet (e.g., H. sapiens). As an exception, the genus names should be written in full (a) where they form the first word of a sentence or (b) when only the genus name is used or (c) if several genera with the same initials can lead to confusion or (d) in headings. English common names of species and higher taxa may be used in addition to scientific names. For the convenience of the journal’s international readership, both common AND scientific name should be given together when the common name is used the first time in the title, abstract, main text or table/figure legends of a manuscript. Lower-case initial letters are used for each part of the common names of species, genera, families and all other taxonomic levels (e.g., crabeater seal, blue whale, mountain maple, zebra, bacteria), except where they contain a proper name (e.g., Greenland shark, Przewalski's horse, Amurtiger). Contrary to these general rules of spelling for mammals, insects, fish, and other life forms, the International Ornithologist's Union (IOU) recommends that the words of an official commmon bird name begin with capital letters (e.g., Chinstrap Penguin). Scientific names of higher taxonomic levels (family, order, class, phylum or division, and kingdom; e.g., Ophiuridae, Copepoda, Arthropoda, etc.) should be capitalized but not italicized. However, English common names derived from scientific taxon names, e.g., “cetaceans” for members of the infraorder Cetacea, are not capitalized.
      5. If supplying any additional information (in supplementary tables, figures, spreadsheets, video, audio, etc.) as Electronic Supplementary Material (ESM), the text must make specific mention of the ESM as a citation, similar to that of figures and tables. Refer to the supplementary files as “Online Resource”, e.g., "... as shown in the animation (Online Resource 3)", “... additional data are given in Online Resource 4”, and name the files consecutively, e.g. “ESM_3.mpg”, “ESM_4.pdf” (see Polar Biology's website at http://www.springer.com/300/, link 'Instructions for Authors > Electronic Supplementary Material', for more details on this matter).
      6. Please make sure that text, tables and figures of the revised ms will be submitted as appropriate EDITABLE source files (this is necessary to be released to production), e.g., text and tables in Word (NOT Excel!), WordPerfect, RTF, TXT, or TeX (if your paper is in LaTeX, we also require the style files), figures in TIFF, GIF, JPEG, EPS, Postscript, PICT, Excel and PowerPoint. See Polar Biology's website at www.springer.com/300, links 'Instructions for Authors > Text' and 'Instructions for Authors > Artwork', for more detailed information on format issues. Moreover, please note that uploading PDF files (except for ESM; see Polar Biology's website at http://www.springer.com/300/, link 'Instructions for Authors > Electronic Supplementary Material') at this stage will cause delays should your ms be finally be accepted for publication.
      7. Finally, please note that, while color figures are free of charge for the online publication, you have to pay for them in the printed version (flat fee of 950 Euros/1150 US Dollars, irrespective of the number of color figures). If black and white will be shown in the print version, make sure that the main information will still be visible, as many colors are not distinguishable from one another when converted to black and white (a simple way to check this is to make a xerographic copy to see if the necessary distinctions between the different colors are still apparent). You might also consider substituting all colors by shades of gray (see http://www.springer.com/300/, link 'Instructions for Authors > Artwork', for more details on this matter).

**** REVIEWERS' COMMENTS
     - [ ] Reviewer #1 (Dayton):
       I appreciate being asked to review this manuscript even though I am emphatically not a taxonomist! Note that this is not a formal taxonomic document; I think it is more an interesting and important work in progress. I know some of the authors and have immense respect for them and would not dare to criticize their work. The only reason I am willing to comment on the manuscript is that I agree with the introduction statement about this genus being extremely important to the Antarctic benthic ecosystem, and I feel I have some sympathy for some of these species having struggled with them off and on for almost 50 years. But emphatically, this is not a normal review because I don’t understand either the math or the chemistry. Really this is a very long discussion of why I consider this a very important paper to have in the literature. It is a very clear discussion of the taxonomy of one of the most important but difficult groups in the Antarctic. I think that the general benthic community would appreciate the learning about the genetic relationships of these common and important sponges.
       So, to the Editor: I think that this paper offers valuable information to those working on the Antarctic benthos and my vote is to accept it. I suggest that the authors switch the references to our papers. I think that our last 2016 JEMBE paper is more appropriate here, especially the supplements. In addition, there is a consistent misspelling as I think that R. levi should be R. levis. Finally, while two of the authors wrote the paper recovering R. podagrosa it is not cited, and it has a good discussion of some of its defining characters. In terms of its distribution and abundance I consider this to be one of the most important species in the Antarctic and this would be an excellent place to discuss it even without the molecular information.
       The rest of this long-winded review is to the authors, some of whom are good friends, in hopes of influencing them not to lump these species in the future. I articulate these thoughts because I have been thinking about them for years as we struggled with the correct identification of R. podagrosa that I “knew” was a real species based on life history biology and other obvious characteristics such as its softness.
       So first I offer some personal background to what is more of a commentary than a review. I am a child of the 1950s and my taxonomy was idiosyncratic to the groups of interest. I was not exposed to any underlying philosophy of taxonomy but understood that the world was monophyletic and all the species evolved via Darwin’s selection on the DNA that was just then being discovered, but the groups had their own literature based on very different morphological characters. About that time computers were coming and I remember Paul Ehrlich writing a paper denying that species exist and for a decade or so the computer guys called all species OTUs! Then the DNA folks came and have not left because it really is a powerful tool (as is cladistics), and together they do a great job of with phylogenetic relationships. But I am not clear that even these powerful tools really define the old fashioned species concept for large animals classically considered as being – in principle -reproductively isolated.
       Ernst Mayr’s book “Animal Species and Evolution” came out in the early 60s and finally there was a general overview that made sense to me as I struggled with the definitions of species, genera, families, etc. The reason I bring up this ancient and personal history is that Mayr spent a lot of time talking about characters and how there were many species for which the classical characters could not differentiate obviously different (reproductively isolated) species – indeed, I remember long discussion about characters varying over space and time and the need to use as many hints as possible to characterize a “biological species” (meaning reproductively isolated even if the isolation can not be tested for many reasons).
       This manuscript makes the argument that the Rossella are monophyletic with a clear genetically defined R. antarctica and an R. racovitzae flock that cannot be differentiated with molecular tools. The authors are careful not to lump the species in the R. racovitzae clade (R. nuda, R. fibulata, R. levi(s) with R. racovitzae) and I assume like most other clades of species derived from a common ancestor, they are still good species (such as Darwin’s finches). Here the species flock is defined as “monophyletic, diverse (morphologically, ecologically, and taxonomically) assemblages of closely related species which evolved rapidly within an area where they are endemic and ecologically dominant (Lecointre et al. 2013). The R. racovitzae species flock includes 4 out of 5 species here sampled, these species are endemic to Antarctica, are morphologically diverse and appear to have evolved rapidly as judged by their poly- or paraphyletic status (observed here) and their biogeographic history.”
       The Rossella are by far my favorite genus and I have always thought I was extremely lucky to have had the pleasure of working with them. Many think the Hexactinellida might be the first metazoans (in any case, they are very old and their fossils are easily recognized over some half a billion years) and I know that they are very different from other sponges. And as the authors discuss so clearly, the Rossella are particularly interesting because they are restricted to the Antarctic and are ecologically important. I had accepted a set of names from Koltun and with some false starts and problems, come to recognize different species living adjacent to each other in my area. I was dismayed when Koltun basically lumped them all, and relieved when Tendal and Barthel recovered most of the species except what I now consider R. podagrosa, the one species that lives in close proximity with the others (at McMurdo) and in ecological respects is very different. But then I learned that the molecular biologists were lumping the Rossella again because the DNA does not sort out into nice species. In my mind these “morphological” species may have been reproductively isolated for some 30 million years (or not, possibly they are recently derived), and I don’t think all of them should be synonymized. Perhaps some are not good species, but I think many are, especially the ones you worked on. However, of your species, I think I know R. nuda, but recently I have lost my confidence although in the literature it does seem to be a good species.
       I am comfortable with the treatment and to my old fashioned perspective it is very much in line with the old Mayr discussions of defining a species. At this point what we most need is more natural history to help us learn to be sensitive to what the organisms are trying to tell us. I write all of this because I see a future risk that other workers become dazzled by that the molecular analyses when they need pay more attention to the genetic markers that are used. I think that this is exactly what they authors say in the Conclusion section.
       One final comment, without duplicating Barthel and Tendal it would be helpful for readers of this journal if you could help us better understand the morphological differences that we can actually see in the field. They ARE different. Their morphology is consistently different, as is their life history biology and “ecological niches” such as I can understand them. Some of the differences that we see are subtle such as the relationship of spicules and conules or long anchoring spicules seen for Rossella racovitzae. Biologists are becoming far too specialized and I strongly urge the authors to look beyond the test tubes at the real animals as seen in so many excellent photos. Systematics is one of the specialties with their own traditions, but please remember that the rest of us rely on being able to define species in the field. All of ecology is based on efforts to understand the processes determining the distribution and abundance of species in nature, not in test tubes or computers. It would be a huge service if you would try to bridge this gap with an effort to help us identify the species we study. I think a few succinct morphological descriptions with, if possible, color photographs would be immensely helpful to the audience of this journal (and almost everybody else – the paper would become an Antarctic classic!). I tried to do this with our supplement, but it is fatally flawed because I wrote it and I am utterly ignorant of real taxonomy! You are some of the best in the world, and if you wrote something like this, it would have all of your prestige and would be extremely valuable.
     - [ ] Reviewer #2:
       It is a very interesting MS! The situation with Rossella racovitzae is extraordinary but I have no hesitations that it is so. It is possible to ague with some theoretical conclusions but it is not that important being rather a subject for future investigations and the MS should be published as it is. I have not found any minor parts in the text to be corrected.
     - [ ] Reviewer #3:
       This paper sets out to understand if the morphological species of Rosella correspond to molecular species. Unfortunately they do not, and yet the authors are reluctant to explore what this really means. Thus they leap to the conclusion of a species flock, without considering that the taxonomy of Rosella was just oversplit, or the morphology just wasn't understood properly. If the monophyly of Rosella is linked with the opening of the Drake Passage, as the authors suggested, the subsequent diversification of the racovitzae clade is incongruent with the existence of the well-supported and characterized species R. antarctica. This is not explored or explained.
       There is also a lot of discussion about total evidence (l168), but only molecular data is used to build the tree.

       I feel like it would be very informative to explore how much variation exists within R. antarctica? That would help understand how much variation might be naturally occurring in its sister species.

       Overall this work is much needed, but is not yet the contribution that it could be.

       Other suggestions:

       P2, l44. If Rosella does dominate, how does it increase heterogeneity? Dominant species increase homogeneity.

       P2, l44-47. Sentence could be reconstructed for greater clarity.

       P3, l64-68. These sentences are completely circular based on the point above.

       P3, l69. of = with, and the word important is used twice.

       P3, l72, the concept of circum-antarctic species isn't really revisited based on the results

       P4, l80. SO wasn't defined earlier in the ms.

       P4, l97. Very low annealing!!

       P5, l112. Please justify manual alignment and removing unalignable regions. This isn't repeatable, and so isn't testable science. There are programs to make this repeatable, which is preferable.

       P5, l123. How did you carry out Bayes analyses in RAxML????!!!

       P5, l124. How did you select the model?

       P6, l144. What about the model for COI?

       P7, l162-164. Pretty poorly explained.

       P7, l168. This whole section is tricky in the sense that there is no feel for support values. I understand its hard to summarise, but I think you should only discuss relationships that are strongly supported.

       P8, l189, 195, 197 etc etc. Not total evidence. Only molecular data. Plaese refer to accordingly.

       P8, l195, 198. 50-80% is not the range in the figure that is referred to as moderate. 50-70% is considered not supported.

       P10, l230. "to some extent correspond to the described species". To some extent just doesn't instill confidence (which is correct, based on results). Its just that the discussion seems to grow in confidence.

       P10, l242.Yes, it could reflect recent speciation, but how about exploring the alternate explanation that its just one variable species.

       P11, l254. What about calling them paraphyletic species?

       P11, l257. Synonymization spelled incorrectly. And why would synonymization be such a bad idea? If that's the truth…why is it so bad?

       Figure 2. total evidence is not what is shown here. It's a concatenated data set. Don't discuss outgroup relationships that are not being tested. Completely artificial.

       Figure 3. It says here that support values are present in Fig 1. But that's not correct. There are only ranges there.   

** TODO CBAS Transcriptome [0/3]
   - [ ] Add table legends to GO term analysis results
   - [ ] Implement pfam enrichment in rmarkdown document
   - [ ] Start writing the Introduction
** TODO CBAS Metagenome [0/1]
   - [ ] Prepare perl script to filter the nanopore reads mapped by graphmap 
** TODO Revise Leptogorgia MS [0/6]
   - [ ] Intro
   - [ ] M&M
   - [ ] Results
   - [ ] Discussion
   - [ ] Rest
** TODO Submit Gaurav's MS3 to PeerJ?




