#+STARTUP: overview
#+STARTUP: hidestars

* Tasks
** DONE Test org-mode install
   CLOSED: [2017-01-04 Wed 15:33]
** TODO How to org-mode
  More about [[http://doc.norang.ca/org-mode.html][here]]
*** Key combinations:
  Shift+Alt+Enter = creates a ** line
  * create headings and subheadings
  Ctrl+c Ctrl+t tags a TODO as DONE and adds a time stamp
  "[[link][description]" creates a link with the text given in "description" visible
  Shift+TAB opens or closes all sections
  Ctrl+c Ctrl+c to add TAGS
  Ctrl+c Ctrl+x Ctrl+i Clock-IN
  Ctrl+c Ctrl+x Ctrl+o Clock OUT

** TODO Finish Habil report!
** TODO Edit and Resubmit Polar Biology Manuscript
*** Description
    MS on the phylogeny of /Rossella/ was sent to Polar Biology and is currently accepted with changes. These changes have to be done and the MS needs to be resubmitted.
    
*** Changes to be done by section:
    

** TODO CBAS Transcriptome [0/3]
   - [ ] Add table legends to GO term analysis results
   - [ ] Implement pfam enrichment in rmarkdown document
   - [ ] Start writing the Introduction
** TODO CBAS Metagenome [0/1]
   - [ ] Prepare perl script to filter the nanopore reads mapped by graphmap 
** TODO Revise Leptogorgia MS [0/6]
   - [ ] Intro
   - [ ] M&M
   - [ ] Results
   - [ ] Discussion
   - [ ] Rest
** TODO Submit Gaurav's MS3 to PeerJ?




